name: xiaomi_scale_example
description: Demonstrates how to use the xiaomi_scale plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  http: ^0.13.0
  flutter_bluetooth_serial: ^0.0.4
  permission_handler: ^5.0.1+1
  xiaomi_scale:
    path: ../
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fluttertoast: ^7.1.6
  flutter_spinkit: "^4.1.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
